name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Build
        run: |
          python3 -m pip install --user build
          python3 -m build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write
    environment:
      name: release
      url: https://pypi.org/p/yt-dlp-danmaku
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
